### ISSUE TITLE
Display features in map as additional overlay

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-streaming-kmeans#22]
Once #18 is done, the map could make a `/features` request to get back the last N features (e.g. 100) that have been assigned to clusters.

Likely we'd want these to use a different color, and have much smaller circles.

**Comment by vmagotra** [comment]
@kkrugler - Done - please validate and close if it looks okay to you.

**Comment by kkrugler** [comment]
lgtm
