### ISSUE TITLE
Use cluster size to alter the circle size in the map

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/flink-streaming-kmeans#24]
Once #23 is done, we can use this to adjust the size of the cluster's circle.

**Comment by kkrugler** [comment]
Currently I'm returning a new `"size": <number of features>` field for each point in the response, but that's causing MapBox to fail (as expected). I think [this link](https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/) might have details on what to return to provide appropriate styling.

It's also interesting that they directly specify a URL source (or so it seems):

``` json
        'source': {
            'type': 'vector',
            'url': 'mapbox://examples.8fgz4egr'
        },
```

So maybe we can skip the `XMLHttpRequest` stuff.

**Comment by vmagotra** [comment]
I modified the tool to return `"size"`as a property, 

    "properties": {
				"size": <value>
			}

which can then be queried using the mapbox `["get", <name of property>]` expression. Currently the size is used directly to set the circle-radius. In the future we may want to use some kind of formula to calculate the radius based on the size.
